// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Model.Entities.Sach.LichSuGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("LoaiGia")
                        .HasColumnType("bit");

                    b.Property<int>("SachId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SachId");

                    b.ToTable("LichSuGias");
                });

            modelBuilder.Entity("Model.Entities.Sach.NhaXuatBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenNxb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VietTat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhaXuatBans");
                });

            modelBuilder.Entity("Model.Entities.Sach.Sach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NxbId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TenSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("NxbId");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("Model.Entities.Sach.SachTacGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SachId")
                        .HasColumnType("int");

                    b.Property<int>("TacGiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SachId");

                    b.HasIndex("TacGiaId");

                    b.ToTable("SachTacGias");
                });

            modelBuilder.Entity("Model.Entities.Sach.SachTheLoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SachId")
                        .HasColumnType("int");

                    b.Property<int>("TheLoaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SachId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("SachTheLoais");
                });

            modelBuilder.Entity("Model.Entities.Sach.TacGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ButDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TacGias");
                });

            modelBuilder.Entity("Model.Entities.Sach.TheLoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenTheLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TheLoais");
                });

            modelBuilder.Entity("Model.Entities.Sach.LichSuGia", b =>
                {
                    b.HasOne("Model.Entities.Sach.Sach", "Sach")
                        .WithMany("LichSuGias")
                        .HasForeignKey("SachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("Model.Entities.Sach.Sach", b =>
                {
                    b.HasOne("Model.Entities.Sach.NhaXuatBan", "Nxb")
                        .WithMany("Sachs")
                        .HasForeignKey("NxbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nxb");
                });

            modelBuilder.Entity("Model.Entities.Sach.SachTacGia", b =>
                {
                    b.HasOne("Model.Entities.Sach.Sach", "Sach")
                        .WithMany("SachTacGias")
                        .HasForeignKey("SachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Sach.TacGia", "TacGia")
                        .WithMany("SachTacGias")
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("Model.Entities.Sach.SachTheLoai", b =>
                {
                    b.HasOne("Model.Entities.Sach.Sach", "Sach")
                        .WithMany("SachTheLoais")
                        .HasForeignKey("SachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Sach.TheLoai", "TheLoai")
                        .WithMany("SachTheLoais")
                        .HasForeignKey("TheLoaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("Model.Entities.Sach.NhaXuatBan", b =>
                {
                    b.Navigation("Sachs");
                });

            modelBuilder.Entity("Model.Entities.Sach.Sach", b =>
                {
                    b.Navigation("LichSuGias");

                    b.Navigation("SachTacGias");

                    b.Navigation("SachTheLoais");
                });

            modelBuilder.Entity("Model.Entities.Sach.TacGia", b =>
                {
                    b.Navigation("SachTacGias");
                });

            modelBuilder.Entity("Model.Entities.Sach.TheLoai", b =>
                {
                    b.Navigation("SachTheLoais");
                });
#pragma warning restore 612, 618
        }
    }
}
